# Generated by Django 4.2.13 on 2024-06-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_quantity_alter_product_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOption2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option2",
                        to="product.product",
                        verbose_name="Product Option 2",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductOption1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option1",
                        to="product.product",
                        verbose_name="Product Option 1",
                    ),
                ),
            ],
        ),
    ]
