# Generated by Django 4.2.13 on 2024-06-20 19:15

import apps.product.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_productoption2_productoption1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productoption1",
            old_name="option",
            new_name="option_1",
        ),
        migrations.AddField(
            model_name="productoption1",
            name="option_1_thumbnail",
            field=models.ImageField(
                blank=True, upload_to=apps.product.models.upload_to_option_folder
            ),
        ),
        migrations.AddField(
            model_name="productoption1",
            name="option_2",
            field=models.CharField(default="temp", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productoption1",
            name="option_2_thumbnail",
            field=models.ImageField(
                blank=True, upload_to=apps.product.models.upload_to_option_folder
            ),
        ),
        migrations.AlterField(
            model_name="productoption1",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_1",
                to="product.product",
                verbose_name="Product Option 1",
            ),
        ),
        migrations.AlterField(
            model_name="productoption2",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_2",
                to="product.product",
                verbose_name="Product Option 2",
            ),
        ),
    ]
