# Generated by Django 4.2.13 on 2024-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_rename_option_productoption1_option_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption1",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
