# Generated by Django 4.2.13 on 2024-06-20 19:31

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_productoption1_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoption1",
            name="option_2_thumbnail",
            field=models.ImageField(
                blank=True, upload_to=apps.product.models.upload_to_option2_folder
            ),
        ),
    ]
